import { Router } from "express";
import slugify from "slugify";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";
import { asyncHandler, created, ok } from "../lib/http.js";
import { requireAdmin, requireAuth } from "../middleware/auth.js";
export const catalogRoutes = Router();
export const adminCatalogRoutes = Router();
const productInclude = { images: { orderBy: { displayOrder: "asc" as const } }, variants: true, category: true, brand: true, reviews: true };
catalogRoutes.get("/products", asyncHandler(async (req, res) => { const q = z.object({ search: z.string().optional(), category: z.string().optional(), brand: z.string().optional(), min: z.coerce.number().optional(), max: z.coerce.number().optional(), sort: z.string().optional(), page: z.coerce.number().default(1), limit: z.coerce.number().default(12) }).parse(req.query); const where: any = { status: "ACTIVE", ...(q.search && { OR: [{ name: { contains: q.search, mode: "insensitive" } }, { description: { contains: q.search, mode: "insensitive" } }] }), ...(q.category && { category: { slug: q.category } }), ...(q.brand && { brand: { slug: q.brand } }), ...((q.min || q.max) && { regularPrice: { gte: q.min, lte: q.max } }) }; const orderBy = q.sort === "price-low" ? { regularPrice: "asc" as const } : q.sort === "price-high" ? { regularPrice: "desc" as const } : q.sort === "best-selling" ? { bestSeller: "desc" as const } : { createdAt: "desc" as const }; const [items, total] = await Promise.all([prisma.product.findMany({ where, include: productInclude, orderBy, skip: (q.page - 1) * q.limit, take: q.limit }), prisma.product.count({ where })]); ok(res, items, { total, page: q.page, pages: Math.ceil(total / q.limit) }); }));
catalogRoutes.get("/products/:slug", asyncHandler(async (req, res) => ok(res, await prisma.product.findUniqueOrThrow({ where: { slug: req.params.slug }, include: productInclude }))));
catalogRoutes.get("/categories", asyncHandler(async (_req, res) => ok(res, await prisma.category.findMany({ where: { active: true }, include: { children: true }, orderBy: { displayOrder: "asc" } }))));
catalogRoutes.get("/brands", asyncHandler(async (_req, res) => ok(res, await prisma.brand.findMany({ where: { active: true }, orderBy: { name: "asc" } }))));
adminCatalogRoutes.use(requireAuth, requireAdmin);
adminCatalogRoutes.get("/products", asyncHandler(async (_req, res) => ok(res, await prisma.product.findMany({ include: productInclude, orderBy: { updatedAt: "desc" } }))));
adminCatalogRoutes.post("/products", asyncHandler(async (req, res) => { const body = z.object({ name: z.string(), sku: z.string(), description: z.string(), shortDescription: z.string().optional(), categoryId: z.string(), brandId: z.string().optional(), regularPrice: z.number(), salePrice: z.number().optional(), stock: z.number().default(0), featured: z.boolean().default(false), bestSeller: z.boolean().default(false), newArrival: z.boolean().default(false), images: z.array(z.object({ url: z.string(), alt: z.string().optional(), isPrimary: z.boolean().optional(), displayOrder: z.number().optional() })).default([]) }).parse(req.body); const { images, ...product } = body; created(res, await prisma.product.create({ data: { ...product, slug: slugify(body.name, { lower: true }), images: { create: images } }, include: productInclude })); }));
adminCatalogRoutes.put("/products/:id", asyncHandler(async (req, res) => ok(res, await prisma.product.update({ where: { id: req.params.id }, data: req.body, include: productInclude }))));
adminCatalogRoutes.delete("/products/:id", asyncHandler(async (req, res) => ok(res, await prisma.product.delete({ where: { id: req.params.id } }))));
adminCatalogRoutes.get("/categories", asyncHandler(async (_req, res) => ok(res, await prisma.category.findMany({ include: { children: true, parent: true }, orderBy: { displayOrder: "asc" } }))));
adminCatalogRoutes.post("/categories", asyncHandler(async (req, res) => created(res, await prisma.category.create({ data: { ...req.body, slug: req.body.slug || slugify(req.body.name, { lower: true }) } }))));
adminCatalogRoutes.put("/categories/:id", asyncHandler(async (req, res) => ok(res, await prisma.category.update({ where: { id: req.params.id }, data: req.body }))));
adminCatalogRoutes.delete("/categories/:id", asyncHandler(async (req, res) => ok(res, await prisma.category.delete({ where: { id: req.params.id } }))));
adminCatalogRoutes.get("/brands", asyncHandler(async (_req, res) => ok(res, await prisma.brand.findMany())));
adminCatalogRoutes.post("/brands", asyncHandler(async (req, res) => created(res, await prisma.brand.create({ data: { ...req.body, slug: req.body.slug || slugify(req.body.name, { lower: true }) } }))));
