import { Router } from "express";
import { prisma } from "../lib/prisma.js";
import { asyncHandler, ok } from "../lib/http.js";
import { requireAdmin, requireAuth } from "../middleware/auth.js";
export const cmsRoutes = Router();
export const adminCmsRoutes = Router();
cmsRoutes.get("/site-settings", asyncHandler(async (_req, res) => ok(res, await prisma.siteSetting.findMany())));
cmsRoutes.get("/homepage", asyncHandler(async (_req, res) => ok(res, { sections: await prisma.homepageSection.findMany({ where: { active: true }, orderBy: { displayOrder: "asc" } }), banners: await prisma.banner.findMany({ where: { active: true }, orderBy: { displayOrder: "asc" } }) })));
cmsRoutes.get("/pages/:slug", asyncHandler(async (req, res) => ok(res, await prisma.page.findFirstOrThrow({ where: { slug: req.params.slug, status: "PUBLISHED" } }))));
adminCmsRoutes.use(requireAuth, requireAdmin);
adminCmsRoutes.put("/site-settings", asyncHandler(async (req, res) => { const entries = Object.entries(req.body as Record<string, unknown>); await prisma.$transaction(entries.map(([key, value]) => prisma.siteSetting.upsert({ where: { key }, update: { value: value as any }, create: { key, value: value as any } }))); ok(res, await prisma.siteSetting.findMany()); }));
adminCmsRoutes.put("/homepage", asyncHandler(async (req, res) => { await prisma.$transaction((req.body.sections ?? []).map((s: any) => s.id ? prisma.homepageSection.update({ where: { id: s.id }, data: s }) : prisma.homepageSection.create({ data: s }))); ok(res, await prisma.homepageSection.findMany({ orderBy: { displayOrder: "asc" } })); }));
adminCmsRoutes.get("/banners", asyncHandler(async (_req, res) => ok(res, await prisma.banner.findMany())));
adminCmsRoutes.post("/banners", asyncHandler(async (req, res) => ok(res, await prisma.banner.create({ data: req.body }))));
adminCmsRoutes.put("/banners/:id", asyncHandler(async (req, res) => ok(res, await prisma.banner.update({ where: { id: req.params.id }, data: req.body }))));
adminCmsRoutes.delete("/banners/:id", asyncHandler(async (req, res) => ok(res, await prisma.banner.delete({ where: { id: req.params.id } }))));
adminCmsRoutes.get("/pages", asyncHandler(async (_req, res) => ok(res, await prisma.page.findMany())));
adminCmsRoutes.post("/pages", asyncHandler(async (req, res) => ok(res, await prisma.page.create({ data: req.body }))));
adminCmsRoutes.put("/pages/:id", asyncHandler(async (req, res) => ok(res, await prisma.page.update({ where: { id: req.params.id }, data: req.body }))));
