import bcrypt from "bcryptjs";
import slugify from "slugify";
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
const img = (id: string) => `https://images.unsplash.com/${id}?q=80&w=1200&auto=format&fit=crop`;
async function main(){
  const adminPassword = process.env.ADMIN_SEED_PASSWORD ?? "ChangeMe123!";
  await prisma.user.upsert({ where:{email:"admin@example.com"}, update:{}, create:{ name:"Store Admin", email:"admin@example.com", role:"ADMIN", passwordHash: await bcrypt.hash(adminPassword,12) } });
  const customer = await prisma.user.upsert({ where:{email:"customer@example.com"}, update:{}, create:{ name:"Demo Customer", email:"customer@example.com", phone:"9999999999", passwordHash: await bcrypt.hash("Customer123!",12) } });
  const names=["Home Decor","Wall Decor","Wooden Decor","Lamps","Stationery","Pens","Journals","Desk Accessories","Kids Clothing","Boys","Girls"];
  const cats:any[]=[]; for(const [i,name] of names.entries()){ cats.push(await prisma.category.upsert({ where:{slug:slugify(name,{lower:true})}, update:{}, create:{ name, slug:slugify(name,{lower:true}), description:`Premium ${name.toLowerCase()} collection`, displayOrder:i } })); }
  const brand = await prisma.brand.upsert({ where:{slug:"aurelia-home"}, update:{}, create:{ name:"Aurelia Home", slug:"aurelia-home" } });
  const products = ["Wooden Wall Shelf","Handwoven Table Runner","Brass Desk Lamp","Ceramic Planter Set","Minimal Journal Pack","Fountain Pen Classic","Kids Cotton Kurta","Girls Floral Dress","Boys Linen Shirt","Marble Candle Holder","Rattan Storage Basket","Desk Organizer Tray","Abstract Wall Art","Reading Floor Lamp","Travel Notebook Trio"];
  for(const [i,name] of products.entries()){ const category=cats[i%cats.length]; await prisma.product.upsert({ where:{sku:`SKU-${1000+i}`}, update:{}, create:{ name, slug:slugify(name,{lower:true}), sku:`SKU-${1000+i}`, shortDescription:`Beautifully made ${name.toLowerCase()}.`, description:`A premium ${name.toLowerCase()} built for modern Indian homes and gifting.`, categoryId:category.id, brandId:brand.id, regularPrice:699+i*140, salePrice:i%3===0?599+i*110:null, costPrice:350+i*50, stock:8+i, lowStockThreshold:5, featured:i<8, bestSeller:i%4===0, newArrival:i>9, hsnCode:"4421", gstPercentage:18, images:{create:[{url:img(["photo-1505693416388-ac5ce068fe85","photo-1513519245088-0e12902e5a38","photo-1507473885765-e6ed057f782c","photo-1485955900006-10f4d324d411"][i%4]), isPrimary:true, displayOrder:0}]}, variants:{create:i%2===0?[{sku:`SKU-${1000+i}-BLK`, price:699+i*140, stock:4, attributes:{color:"Black",size:"M"}},{sku:`SKU-${1000+i}-WHT`, price:749+i*140, stock:5, attributes:{color:"White",size:"L"}}]:[]} } }); }
  await prisma.homepageSection.deleteMany();
  await prisma.homepageSection.createMany({ data:[{type:"hero",title:"Premium Finds For Everyday Living",subtitle:"CMS controlled",description:"Curated decor, stationery, and kids clothing. Every headline, banner, and section comes from the database.",image:img("photo-1494438639946-1ebd1d20bf85"),buttonLabel:"Shop the edit",buttonUrl:"/shop",displayOrder:1,active:true},{type:"categories",title:"Shop by category",subtitle:"Organized collections",description:"Enable, reorder, and edit homepage sections from admin.",image:img("photo-1524758631624-e2822e304c36"),displayOrder:2,active:true},{type:"offers",title:"Festive offers",subtitle:"Limited time",description:"Use coupons and banners to run campaigns without code changes.",image:img("photo-1512909006721-3d6018887383"),displayOrder:3,active:true}] });
  await prisma.siteSetting.upsert({ where:{key:"store"}, update:{ value:{name:"Aurelia", phone:"+91 99999 99999", email:"hello@example.com", currency:"INR", freeShippingAbove:999, shippingCharge:99} }, create:{ key:"store", group:"general", value:{name:"Aurelia", phone:"+91 99999 99999", email:"hello@example.com", currency:"INR", freeShippingAbove:999, shippingCharge:99} } });
  await prisma.page.upsert({ where:{slug:"about-us"}, update:{}, create:{ title:"About Us", slug:"about-us", content:"<p>A database-editable story for the storefront.</p>", status:"PUBLISHED" } });
  await prisma.coupon.upsert({ where:{code:"WELCOME10"}, update:{}, create:{ code:"WELCOME10", discountType:"PERCENTAGE", discountAmount:10, minimumPurchase:999, maximumDiscount:500, usageLimit:100, customerUsageLimit:1, startDate:new Date(), expiryDate:new Date(Date.now()+30*864e5), active:true } });
  await prisma.order.create({ data:{ orderNumber:`ORD-SEED-${Date.now()}`, userId:customer.id, billingAddress:{city:"Ahmedabad"}, shippingAddress:{city:"Ahmedabad"}, subtotal:1299, shipping:0, total:1299, paymentMethod:"COD", status:"CONFIRMED", items:{create:{ productId:(await prisma.product.findFirstOrThrow()).id, name:"Wooden Wall Shelf", sku:"SKU-1000", quantity:1, price:1299, total:1299 } } } });
}
main().finally(()=>prisma.$disconnect());
